### PR TITLE
use spring template resolver and view

### PR DESCRIPTION
**Pull request by atomfrede**
This is somehow related to #5. It makes use of spring's view resolving mechanism such that the controller can be used in a more spring idiomatic way (e.g. just return a string which denotes the template name).

### CODE REVIEW

**Comment by benjamin-thomas** [comment]
Hello :)

One downside to doing this is this breaks IDE integration. See below:

image

 Prior to this change, IntelliJ was smart enough to recognize a filename and `Control+Click` would jump you straight to the jte template.

I tried to play with various ideas, in an effort to give some hints to IntelliJ so that it could infer the MVC view location, but nothing of value came of it.

Do you have any ideas @atomfrede

**Comment by atomfrede** [comment]
Interesting didn't notice but I understand its not nice. I don't know how intellij is doing their smart things maybe we can give the jte plugin some hints?

**Comment by casid** [comment]
@atomfrede the jte plugin looks for String Literals ending with .jte

However, I think the "Cannot resolve MVC view 'demo'" message comes from the Spring plugin. Probably the Spring plugin would need to learn about jte template resolver to make it work.

**Comment by benjamin-thomas** [comment]
> the jte plugin looks for String Literals ending with .jte

Oh, that's what it was :)

Thank for your input @atomfrede @casid.

While searching for a solution, I saw a lot of Jetbrains tickets regarding this feature breaking over the years so I'm not sure spending time on this would be worth the effort.

I'm not sold on the usefulness of Spring's view resolver feature anyways, so I'm fine doing as before in my test project :)

**Pull request merged**
