### PR TITLE
Spring boot starter usage

### PR DESCRIPTION
**Pull request by atomfrede**
Hi @casid,

you can try the starter via jitpack now (so not intended to be merged). I need to setup release on maven central and some documentation. If you like the outcome we could move the repo under your org as an "official" jte integration.

### CODE REVIEW

**Comment by casid** [comment]
That's awesome!

The easiest way would be to put `jte-spring-boot-starter` in the [jte monorepo](https://github.com/casid/jte), if that'd be okay for you. This way, a new version would be automatically published to maven central whenever a new jte release is done.

Something like:

```xml
<dependency>
    <groupId>gg.jte</groupId>
    <artifactId>jte-spring-boot-starter</artifactId>
    <version>2.0.2-SNAPSHOT</version>
</dependency>
```

What do you think?

**Comment by atomfrede** [comment]
That would be great. Will prepare a pr

**Comment by casid** [comment]
Thank you!

**Comment by atomfrede** [comment]
Closing this and creating a new one with the published artifact.

**Pull request closed without merging**
